### ISSUE TITLE
How could I use this without autoloader or composer ?

### ISSUE THREAD

**Issue by peon501** [zaporylie/php-tripletex#2]
How could I use this without autoloader or composer ?

**Comment by zaporylie** [comment]
No, sorry but no. This package has a dependency in several other packages, hence needs to be managed by composer.

**Comment by peon501** [comment]
Server that I use do not have phar php extension soo I cant install composer

**Comment by peon501** [comment]
that sucks, do u have any ideas how could I write communication ?
could I use curl for communications ?

**Comment by peon501** [comment]
I need at last auth code, other stuff i will do by myself

**Comment by zaporylie** [comment]
> could I use curl for communications ?

Certainly! Here's documentation: https://tripletex.no/v2-docs/

But in this case I would recommend you to use composer on your localhost, where you have total control over the server configuration, commit /vendor directory to the git repository and just pull on remote server. This way you won't need to use composer on the remote server.

**Comment by peon501** [comment]
Yea, prob I will do this :)

**Comment by peon501** [comment]
ok does it work in php 7.2 ?
also I get error

Fatal error: Uncaught Error: Class 'Redis' not found in /opt/lampp/htdocs/php-tripletex-master/vendor/blablacar/redis-client/src/Blablacar/Redis/Client.php:54 Stack trace: #0 /opt/lampp/htdocs/php-tripletex-master/src/Client/Token/RedisTokenStorage.php(40): Blablacar\Redis\Client->connect() #1 /opt/lampp/htdocs/php-tripletex-master/examples/01-auth.php(6): zaporylie\Tripletex\Client\Token\RedisTokenStorage->__construct(Object(Blablacar\Redis\Client)) #2 {main} thrown in /opt/lampp/htdocs/php-tripletex-master/vendor/blablacar/redis-client/src/Blablacar/Redis/Client.php on line 54

**Comment by zaporylie** [comment]
This lib itself **doesn't** require Redis, which you apparently you haven't installed, but **examples do**. 

Drop session_token storage in  https://github.com/zaporylie/php-tripletex/blob/master/examples/01-auth.php#L7 to use **in-memory** session token storage rather than Redis.

**Comment by peon501** [comment]
oh ty

**Comment by peon501** [comment]
where can I set test api url ?

**Comment by peon501** [comment]
Nevermind. I found ty for support
